# Generated by Django 4.1.2 on 2022-10-14 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_feedcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedcomment',
            old_name='tweet',
            new_name='feed',
        ),
    ]
